spring.application.name=Quiz2

spring.datasource.url=jdbc:h2:mem:truckdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=mi_clave_super_secreta_para_jwt_12345678901234567890
jwt.expiration=86400000
